/**
 * 虛擬實習任務庫——寫實向，圍繞常見職場情境。
 * 玩家可無限循環挑戰，每完成一關累積經驗值。
 */
export type Mission = {
  title: string;
  manager: string;
  optionA: string; // 穩健派
  optionB: string; // 直覺派
  successA: string;
  successB: string;
  rewardA: number;
  rewardB: number;
};

export const internMissions: Mission[] = [
  {
    title: "影印機卡紙，全辦公室在看你",
    manager: "（不耐煩）新來的，去處理一下，十分鐘內。",
    optionA: "🅰️ 翻說明書、按步驟拆紙匣處理",
    optionB: "🅱️ 直接連絡總務請維修人員來",
    successA: "✅ 你照 SOP 排除，順手把紙匣補滿。+30 XP",
    successB: "✅ 你判斷不在自己權限內，請對的人處理。+25 XP",
    rewardA: 30, rewardB: 25,
  },
  {
    title: "客戶突然來電飆罵，主管在開會",
    manager: "（短訊）你先接，記住——不要承諾任何事。",
    optionA: "🅰️ 同理傾聽、紀錄重點、承諾回電",
    optionB: "🅱️ 為了息事寧人答應補償方案",
    successA: "✅ 客戶情緒平復，主管回來只需確認。+50 XP",
    successB: "⚠️ 短期止血，但主管得花更多時間善後。+10 XP",
    rewardA: 50, rewardB: 10,
  },
  {
    title: "週會輪到你發言，前一位講超時",
    manager: "（眼神）你三句話講完。",
    optionA: "🅰️ 直接講結論、再補一句佐證",
    optionB: "🅱️ 把原本準備的五頁簡報濃縮念完",
    successA: "✅ 老闆點頭：『就這個方向走。』+45 XP",
    successB: "⚠️ 時間到還沒講完，被打斷。+10 XP",
    rewardA: 45, rewardB: 10,
  },
  {
    title: "同事請你幫忙『順手做一下』",
    manager: "（同事傳訊）這個我下午要交，幫我貼一下表？",
    optionA: "🅰️ 問清楚範圍與時程，再判斷能不能接",
    optionB: "🅱️ 不好意思拒絕，先答應再說",
    successA: "✅ 你列出今天的本份事項，請對方排優先順序。+40 XP",
    successB: "⚠️ 自己加班到八點，本份工作還沒做完。+5 XP",
    rewardA: 40, rewardB: 5,
  },
  {
    title: "主管把信件副本給你，但沒指示",
    manager: "（mail）副本給你參考。",
    optionA: "🅰️ 主動回信簡述你的理解與下一步",
    optionB: "🅱️ 看完歸檔，等主管再說",
    successA: "✅ 主管：『你這樣很省我時間。』+45 XP",
    successB: "⚠️ 三天後主管問進度，才發現你沒接到球。+5 XP",
    rewardA: 45, rewardB: 5,
  },
  {
    title: "供應商寄錯規格的物料",
    manager: "（電話）你看著辦，今天要回覆。",
    optionA: "🅰️ 拍照存證、寄正式信、副本主管",
    optionB: "🅱️ 打給對方窗口口頭協調換貨",
    successA: "✅ 留下完整紀錄，事後追責一目了然。+50 XP",
    successB: "⚠️ 對方答應後反悔，沒有書面證據。+10 XP",
    rewardA: 50, rewardB: 10,
  },
  {
    title: "茶水間聽到別人在抱怨主管",
    manager: "（同事）你也覺得他超機車對吧？",
    optionA: "🅰️ 微笑說『我先回座位』",
    optionB: "🅱️ 加入抱怨，順便講幾句",
    successA: "✅ 你保留了中立空間，誰都不得罪。+35 XP",
    successB: "⚠️ 兩週後話傳到主管耳裡。+0 XP",
    rewardA: 35, rewardB: 0,
  },
  {
    title: "報告檔案臨上線發現有錯字",
    manager: "（兩分鐘後要寄出）",
    optionA: "🅰️ 立刻回報，請窗口稍候三分鐘",
    optionB: "🅱️ 寄出後再補一封更正信",
    successA: "✅ 對方稱讚『負責任』，第二版乾乾淨淨。+40 XP",
    successB: "⚠️ 對方覺得你不嚴謹，下次少給你機會。+10 XP",
    rewardA: 40, rewardB: 10,
  },
  {
    title: "中午訂便當，少了你的",
    manager: "（同事）抱歉漏了你的，你自己叫好嗎？",
    optionA: "🅰️ 笑笑說沒關係，自己外出買",
    optionB: "🅱️ 認真表達『下次請記得我』",
    successA: "✅ 同事注意到你不計較。+25 XP",
    successB: "✅ 邊界感清楚，反而被尊重。+35 XP",
    rewardA: 25, rewardB: 35,
  },
  {
    title: "主管把你的功勞拿去報告",
    manager: "（主管在會議上）這個分析是我做的。",
    optionA: "🅰️ 會後私下提出，請主管未來標註",
    optionB: "🅱️ 當場舉手補充：『這份其實是我做的。』",
    successA: "✅ 主管致歉，下次正式 credit 給你。+50 XP",
    successB: "⚠️ 主管面子掛不住，後續冷處理。+10 XP",
    rewardA: 50, rewardB: 10,
  },
  {
    title: "你發現報表有錯，但已經寄出兩天",
    manager: "（你自己發現）",
    optionA: "🅰️ 主動承認、附正確版、寫明影響",
    optionB: "🅱️ 偷偷改檔案，希望沒人發現",
    successA: "✅ 主管覺得你誠實，反而被信任。+55 XP",
    successB: "⚠️ 兩週後客戶發現，事情擴大。+0 XP",
    rewardA: 55, rewardB: 0,
  },
  {
    title: "客戶要求加 LINE 私聊",
    manager: "（客戶）公司信好慢，加我 LINE 比較快啦。",
    optionA: "🅰️ 委婉解釋公司紀錄要求，留在 email",
    optionB: "🅱️ 加了，反正比較好溝通",
    successA: "✅ 客戶尊重專業，往來都有憑據。+40 XP",
    successB: "⚠️ 半夜訊息、口頭承諾無從追溯。+5 XP",
    rewardA: 40, rewardB: 5,
  },
  {
    title: "新同事問你『要怎麼跟主管相處』",
    manager: "（新同事）你來最久，給點建議吧。",
    optionA: "🅰️ 分享你觀察到的工作節奏、不評論個性",
    optionB: "🅱️ 直接告訴他主管的地雷",
    successA: "✅ 新人快速進入狀況，反過來感謝你。+45 XP",
    successB: "⚠️ 新人不小心轉述，主管覺得你愛說閒話。+5 XP",
    rewardA: 45, rewardB: 5,
  },
  {
    title: "資料庫權限你不該有，但被誤開",
    manager: "（系統）你發現自己可以看到薪資表",
    optionA: "🅰️ 立刻通報資訊部關閉並記錄",
    optionB: "🅱️ 反正沒人知道，看一眼就好",
    successA: "✅ 資訊部記下你的誠信，未來推薦升職。+55 XP",
    successB: "⚠️ 半年後系統稽核被查出，留下紀錄。+0 XP",
    rewardA: 55, rewardB: 0,
  },
  {
    title: "週五下午五點，老闆走過來問『有空嗎？』",
    manager: "（老闆）一件小事，半小時。",
    optionA: "🅰️ 確認是否影響原本下班計畫，誠實溝通",
    optionB: "🅱️ 立刻答應，週末計畫先擺一邊",
    successA: "✅ 老闆說：『那下週一早上吧。』+40 XP",
    successB: "⚠️ 變成下班前固定加班，邊界破了再難修。+10 XP",
    rewardA: 40, rewardB: 10,
  },
  {
    title: "團隊聚餐，你不太喝酒",
    manager: "（同事）來啦一杯，意思一下。",
    optionA: "🅰️ 微笑舉杯，但杯裡是茶",
    optionB: "🅱️ 為了合群乾了三杯",
    successA: "✅ 你保有自己，也沒讓場面尷尬。+35 XP",
    successB: "⚠️ 隔天請病假，主管私下提醒。+5 XP",
    rewardA: 35, rewardB: 5,
  },
  {
    title: "你發現同事在報帳時灌水",
    manager: "（你親眼看到收據被改）",
    optionA: "🅰️ 先跟對方確認，再考慮是否報告",
    optionB: "🅱️ 假裝沒看到，不是你的事",
    successA: "✅ 對方解釋是誤會並更正，事情圓滿。+50 XP",
    successB: "⚠️ 半年後爆出大案，你也被列為知情未報。+0 XP",
    rewardA: 50, rewardB: 0,
  },
  {
    title: "簡報前 30 秒，投影機沒訊號",
    manager: "（會議室全部人在等）",
    optionA: "🅰️ 鎮定請大家先看紙本，邊排查邊講",
    optionB: "🅱️ 緊張到反覆插拔線，氣氛變僵",
    successA: "✅ 你的台風穩，主管當場想推你帶下個案子。+50 XP",
    successB: "⚠️ 簡報延遲十分鐘，被檢討事前測試。+5 XP",
    rewardA: 50, rewardB: 5,
  },
  {
    title: "新人問你能不能幫忙改履歷",
    manager: "（新人）你的文筆好，幫我看一下嘛！",
    optionA: "🅰️ 約一個 15 分鐘的時段認真給回饋",
    optionB: "🅱️ 隨手回幾句，繼續手邊工作",
    successA: "✅ 新人三個月後升上來，跟你成為合作好搭檔。+40 XP",
    successB: "⚠️ 新人覺得你冷淡，往後不再找你。+5 XP",
    rewardA: 40, rewardB: 5,
  },
  {
    title: "你被派去陪老闆見『大人物』，全程要安靜",
    manager: "（出發前主管）你不要亂講話。",
    optionA: "🅰️ 全程做筆記，必要時遞水",
    optionB: "🅱️ 趁機自我介紹爭取曝光",
    successA: "✅ 老闆事後說：『會聽的人很少，下次帶你。』+50 XP",
    successB: "⚠️ 老闆覺得你不知分寸，下次找別人。+5 XP",
    rewardA: 50, rewardB: 5,
  },
];
