/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppMatchRouteImport } from './routes/_app.match'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppCallRouteImport } from './routes/_app.call'
import { Route as AppCafeRouteImport } from './routes/_app.cafe'
import { Route as AppMapMentorIdRouteImport } from './routes/_app.map.$mentorId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMatchRoute = AppMatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AppRoute,
} as any)
const AppCafeRoute = AppCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => AppRoute,
} as any)
const AppMapMentorIdRoute = AppMapMentorIdRouteImport.update({
  id: '/$mentorId',
  path: '/$mentorId',
  getParentRoute: () => AppMapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/cafe': typeof AppCafeRoute
  '/call': typeof AppCallRoute
  '/map': typeof AppMapRouteWithChildren
  '/match': typeof AppMatchRoute
  '/map/$mentorId': typeof AppMapMentorIdRoute
}
export interface FileRoutesByTo {
  '/cafe': typeof AppCafeRoute
  '/call': typeof AppCallRoute
  '/map': typeof AppMapRouteWithChildren
  '/match': typeof AppMatchRoute
  '/': typeof AppIndexRoute
  '/map/$mentorId': typeof AppMapMentorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/cafe': typeof AppCafeRoute
  '/_app/call': typeof AppCallRoute
  '/_app/map': typeof AppMapRouteWithChildren
  '/_app/match': typeof AppMatchRoute
  '/_app/': typeof AppIndexRoute
  '/_app/map/$mentorId': typeof AppMapMentorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cafe' | '/call' | '/map' | '/match' | '/map/$mentorId'
  fileRoutesByTo: FileRoutesByTo
  to: '/cafe' | '/call' | '/map' | '/match' | '/' | '/map/$mentorId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/cafe'
    | '/_app/call'
    | '/_app/map'
    | '/_app/match'
    | '/_app/'
    | '/_app/map/$mentorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/match': {
      id: '/_app/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof AppMatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call': {
      id: '/_app/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cafe': {
      id: '/_app/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof AppCafeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map/$mentorId': {
      id: '/_app/map/$mentorId'
      path: '/$mentorId'
      fullPath: '/map/$mentorId'
      preLoaderRoute: typeof AppMapMentorIdRouteImport
      parentRoute: typeof AppMapRoute
    }
  }
}

interface AppMapRouteChildren {
  AppMapMentorIdRoute: typeof AppMapMentorIdRoute
}

const AppMapRouteChildren: AppMapRouteChildren = {
  AppMapMentorIdRoute: AppMapMentorIdRoute,
}

const AppMapRouteWithChildren =
  AppMapRoute._addFileChildren(AppMapRouteChildren)

interface AppRouteChildren {
  AppCafeRoute: typeof AppCafeRoute
  AppCallRoute: typeof AppCallRoute
  AppMapRoute: typeof AppMapRouteWithChildren
  AppMatchRoute: typeof AppMatchRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCafeRoute: AppCafeRoute,
  AppCallRoute: AppCallRoute,
  AppMapRoute: AppMapRouteWithChildren,
  AppMatchRoute: AppMatchRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
