/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTeacherSignupRouteImport } from './routes/_app.teacher-signup'
import { Route as AppPortfolioRouteImport } from './routes/_app.portfolio'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppManifestoRouteImport } from './routes/_app.manifesto'
import { Route as AppJoinRouteImport } from './routes/_app.join'
import { Route as AppExploreRouteImport } from './routes/_app.explore'
import { Route as AppCallRouteImport } from './routes/_app.call'
import { Route as AppCafeRouteImport } from './routes/_app.cafe'
import { Route as AppTeacherIndexRouteImport } from './routes/_app.teacher.index'
import { Route as AppTeacherClassroomIdRouteImport } from './routes/_app.teacher.$classroomId'
import { Route as AppMapMentorIdRouteImport } from './routes/_app.map.$mentorId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherSignupRoute = AppTeacherSignupRouteImport.update({
  id: '/teacher-signup',
  path: '/teacher-signup',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppManifestoRoute = AppManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => AppRoute,
} as any)
const AppJoinRoute = AppJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AppRoute,
} as any)
const AppCafeRoute = AppCafeRouteImport.update({
  id: '/cafe',
  path: '/cafe',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherIndexRoute = AppTeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => AppRoute,
} as any)
const AppTeacherClassroomIdRoute = AppTeacherClassroomIdRouteImport.update({
  id: '/teacher/$classroomId',
  path: '/teacher/$classroomId',
  getParentRoute: () => AppRoute,
} as any)
const AppMapMentorIdRoute = AppMapMentorIdRouteImport.update({
  id: '/$mentorId',
  path: '/$mentorId',
  getParentRoute: () => AppMapRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/cafe': typeof AppCafeRoute
  '/call': typeof AppCallRoute
  '/explore': typeof AppExploreRoute
  '/join': typeof AppJoinRoute
  '/manifesto': typeof AppManifestoRoute
  '/map': typeof AppMapRouteWithChildren
  '/portfolio': typeof AppPortfolioRoute
  '/teacher-signup': typeof AppTeacherSignupRoute
  '/map/$mentorId': typeof AppMapMentorIdRoute
  '/teacher/$classroomId': typeof AppTeacherClassroomIdRoute
  '/teacher/': typeof AppTeacherIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cafe': typeof AppCafeRoute
  '/call': typeof AppCallRoute
  '/explore': typeof AppExploreRoute
  '/join': typeof AppJoinRoute
  '/manifesto': typeof AppManifestoRoute
  '/map': typeof AppMapRouteWithChildren
  '/portfolio': typeof AppPortfolioRoute
  '/teacher-signup': typeof AppTeacherSignupRoute
  '/': typeof AppIndexRoute
  '/map/$mentorId': typeof AppMapMentorIdRoute
  '/teacher/$classroomId': typeof AppTeacherClassroomIdRoute
  '/teacher': typeof AppTeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cafe': typeof AppCafeRoute
  '/_app/call': typeof AppCallRoute
  '/_app/explore': typeof AppExploreRoute
  '/_app/join': typeof AppJoinRoute
  '/_app/manifesto': typeof AppManifestoRoute
  '/_app/map': typeof AppMapRouteWithChildren
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/teacher-signup': typeof AppTeacherSignupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/map/$mentorId': typeof AppMapMentorIdRoute
  '/_app/teacher/$classroomId': typeof AppTeacherClassroomIdRoute
  '/_app/teacher/': typeof AppTeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cafe'
    | '/call'
    | '/explore'
    | '/join'
    | '/manifesto'
    | '/map'
    | '/portfolio'
    | '/teacher-signup'
    | '/map/$mentorId'
    | '/teacher/$classroomId'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cafe'
    | '/call'
    | '/explore'
    | '/join'
    | '/manifesto'
    | '/map'
    | '/portfolio'
    | '/teacher-signup'
    | '/'
    | '/map/$mentorId'
    | '/teacher/$classroomId'
    | '/teacher'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/cafe'
    | '/_app/call'
    | '/_app/explore'
    | '/_app/join'
    | '/_app/manifesto'
    | '/_app/map'
    | '/_app/portfolio'
    | '/_app/teacher-signup'
    | '/_app/'
    | '/_app/map/$mentorId'
    | '/_app/teacher/$classroomId'
    | '/_app/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher-signup': {
      id: '/_app/teacher-signup'
      path: '/teacher-signup'
      fullPath: '/teacher-signup'
      preLoaderRoute: typeof AppTeacherSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manifesto': {
      id: '/_app/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof AppManifestoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/join': {
      id: '/_app/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof AppJoinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/explore': {
      id: '/_app/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call': {
      id: '/_app/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cafe': {
      id: '/_app/cafe'
      path: '/cafe'
      fullPath: '/cafe'
      preLoaderRoute: typeof AppCafeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/': {
      id: '/_app/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof AppTeacherIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teacher/$classroomId': {
      id: '/_app/teacher/$classroomId'
      path: '/teacher/$classroomId'
      fullPath: '/teacher/$classroomId'
      preLoaderRoute: typeof AppTeacherClassroomIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map/$mentorId': {
      id: '/_app/map/$mentorId'
      path: '/$mentorId'
      fullPath: '/map/$mentorId'
      preLoaderRoute: typeof AppMapMentorIdRouteImport
      parentRoute: typeof AppMapRoute
    }
  }
}

interface AppMapRouteChildren {
  AppMapMentorIdRoute: typeof AppMapMentorIdRoute
}

const AppMapRouteChildren: AppMapRouteChildren = {
  AppMapMentorIdRoute: AppMapMentorIdRoute,
}

const AppMapRouteWithChildren =
  AppMapRoute._addFileChildren(AppMapRouteChildren)

interface AppRouteChildren {
  AppCafeRoute: typeof AppCafeRoute
  AppCallRoute: typeof AppCallRoute
  AppExploreRoute: typeof AppExploreRoute
  AppJoinRoute: typeof AppJoinRoute
  AppManifestoRoute: typeof AppManifestoRoute
  AppMapRoute: typeof AppMapRouteWithChildren
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppTeacherSignupRoute: typeof AppTeacherSignupRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTeacherClassroomIdRoute: typeof AppTeacherClassroomIdRoute
  AppTeacherIndexRoute: typeof AppTeacherIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCafeRoute: AppCafeRoute,
  AppCallRoute: AppCallRoute,
  AppExploreRoute: AppExploreRoute,
  AppJoinRoute: AppJoinRoute,
  AppManifestoRoute: AppManifestoRoute,
  AppMapRoute: AppMapRouteWithChildren,
  AppPortfolioRoute: AppPortfolioRoute,
  AppTeacherSignupRoute: AppTeacherSignupRoute,
  AppIndexRoute: AppIndexRoute,
  AppTeacherClassroomIdRoute: AppTeacherClassroomIdRoute,
  AppTeacherIndexRoute: AppTeacherIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
